export const vehicleTypes = [
  { id: 'all', label: 'All Vehicles', icon: '🚗' },
  { id: 'car', label: 'Cars', icon: '🚗' },
  { id: 'suv', label: 'SUVs', icon: '🚙' },
  { id: 'bike', label: 'Bikes', icon: '🏍️' },
  { id: 'scooter', label: 'Scooters', icon: '🛵' },
  { id: 'truck', label: 'Trucks', icon: '🚛' },
  { id: 'van', label: 'Vans', icon: '🚐' },
  { id: 'boat', label: 'Boats', icon: '⛵' },
  { id: 'rv', label: 'RVs', icon: '🚌' },
]

export const mockVehicles = [
  {
    _id: '1',
    name: 'Tesla Model 3',
    type: 'car',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2023,
    color: 'Midnight Silver',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Electric',
    pricePerDay: 4999,
    pricePerHour: 299,
    available: true,
    rating: 4.9,
    reviewCount: 142,
    location: 'Mumbai, MH',
    images: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80',
      'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80',
    ],
    features: ['AC', 'GPS', 'Bluetooth', 'Autopilot', 'USB-C'],
    description: 'The Tesla Model 3 redefines what a car can be. With over 500km range and instant torque, experience the future of mobility.',
    mileageLimit: 300,
  },
  {
    _id: '2',
    name: 'Royal Enfield Himalayan',
    type: 'bike',
    brand: 'Royal Enfield',
    model: 'Himalayan 450',
    year: 2024,
    color: 'Slate Himalayan Salt',
    seats: 2,
    transmission: 'Manual',
    fuelType: 'Petrol',
    pricePerDay: 1299,
    pricePerHour: 149,
    available: true,
    rating: 4.8,
    reviewCount: 89,
    location: 'Manali, HP',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
      'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&q=80',
    ],
    features: ['ABS', 'Knobby Tyres', 'High Ground Clearance', 'USB Charging', 'Luggage Rack'],
    description: 'Built for adventure. The Himalayan 450 takes you where no ordinary bike dares to go. Mountain passes, forest trails — it handles it all.',
    mileageLimit: 250,
  },
  {
    _id: '3',
    name: 'Toyota Fortuner',
    type: 'suv',
    brand: 'Toyota',
    model: 'Fortuner Legender',
    year: 2023,
    color: 'White Pearl',
    seats: 7,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    pricePerDay: 5999,
    pricePerHour: 399,
    available: true,
    rating: 4.7,
    reviewCount: 203,
    location: 'Delhi, DL',
    images: [
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
    ],
    features: ['4WD', 'AC', '7-Seater', 'Sunroof', 'GPS', 'Leather Seats'],
    description: 'Command every terrain. The Fortuner Legender combines luxury with unstoppable capability — perfect for large groups and long journeys.',
    mileageLimit: 350,
  },
  {
    _id: '4',
    name: 'Honda Activa 6G',
    type: 'scooter',
    brand: 'Honda',
    model: 'Activa 6G',
    year: 2023,
    color: 'Pearl Siren Blue',
    seats: 2,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    pricePerDay: 599,
    pricePerHour: 79,
    available: true,
    rating: 4.5,
    reviewCount: 317,
    location: 'Pune, MH',
    images: [
      'https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&q=80',
    ],
    features: ['CBS', 'LED Lights', 'USB Charging', 'External Fuel Lid'],
    description: 'The most trusted scooter in India. Perfect for city commutes, market runs, and exploring local neighbourhoods without breaking a sweat.',
    mileageLimit: 150,
  },
  {
    _id: '5',
    name: 'Tata Ace EV',
    type: 'truck',
    brand: 'Tata',
    model: 'Ace EV',
    year: 2024,
    color: 'Ice Blue',
    seats: 2,
    transmission: 'Automatic',
    fuelType: 'Electric',
    pricePerDay: 2999,
    pricePerHour: 249,
    available: false,
    rating: 4.4,
    reviewCount: 56,
    location: 'Bengaluru, KA',
    images: [
      'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&q=80',
    ],
    features: ['Electric', 'Load 750kg', 'GPS Tracking', 'Fleet Management'],
    description: 'Eco-friendly cargo movement. Ideal for small business deliveries, event logistics, and moving goods within city limits.',
    mileageLimit: 200,
  },
  {
    _id: '6',
    name: 'Force Traveller 17',
    type: 'van',
    brand: 'Force',
    model: 'Traveller 17',
    year: 2022,
    color: 'Silver',
    seats: 17,
    transmission: 'Manual',
    fuelType: 'Diesel',
    pricePerDay: 4499,
    pricePerHour: 349,
    available: true,
    rating: 4.3,
    reviewCount: 78,
    location: 'Goa',
    images: [
      'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&q=80',
    ],
    features: ['AC', '17-Seater', 'Luggage Space', 'Push-Back Seats'],
    description: 'Move your entire crew in comfort. The Traveller is the go-to van for group outings, pilgrimages, corporate trips, and wedding parties.',
    mileageLimit: 400,
  },
  {
    _id: '7',
    name: 'Yamaha Boats FX Cruiser HO',
    type: 'boat',
    brand: 'Yamaha',
    model: 'FX Cruiser HO',
    year: 2023,
    color: 'Blue/White',
    seats: 3,
    transmission: 'Jet Drive',
    fuelType: 'Petrol',
    pricePerDay: 9999,
    pricePerHour: 999,
    available: true,
    rating: 4.9,
    reviewCount: 34,
    location: 'Goa',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
    ],
    features: ['1800cc Engine', 'Cruise Assist', 'Trim System', 'Boarding Step'],
    description: 'Slice through waves at exhilarating speeds. The FX Cruiser HO delivers championship-level performance on open water.',
    mileageLimit: null,
  },
  {
    _id: '8',
    name: 'Maruti Suzuki Swift',
    type: 'car',
    brand: 'Maruti Suzuki',
    model: 'Swift ZXI+',
    year: 2023,
    color: 'Midnight Blue',
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Petrol',
    pricePerDay: 1899,
    pricePerHour: 179,
    available: true,
    rating: 4.6,
    reviewCount: 445,
    location: 'Hyderabad, TG',
    images: [
      'https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?w=800&q=80',
    ],
    features: ['AC', 'Bluetooth', 'Rear Camera', 'Cruise Control'],
    description: 'Sporty, nimble and fuel-efficient. The Swift is perfect for solo trips, weekend getaways, and navigating tight city streets.',
    mileageLimit: 300,
  },
]

export const stats = [
  { value: '50+', label: 'Vehicle Types' },
  { value: '10K+', label: 'Happy Renters' },
  { value: '100+', label: 'Cities' },
  { value: '4.8★', label: 'Average Rating' },
]

export const testimonials = [
  {
    id: 1,
    name: 'Rahul Mehta',
    role: 'Adventure Traveller',
    text: 'Rented the Himalayan for a week-long Spiti Valley trip. The process was seamless, the bike was in perfect condition. Will definitely book again.',
    rating: 5,
    avatar: 'RM',
  },
  {
    id: 2,
    name: 'Priya Sharma',
    role: 'Business Executive',
    text: 'Needed a luxury SUV for a client meeting. RentRide delivered a spotless Fortuner at 6am. Professional service, no hassles.',
    rating: 5,
    avatar: 'PS',
  },
  {
    id: 3,
    name: 'Arjun Nair',
    role: 'Event Organiser',
    text: 'Booked 3 vans for our company offsite. The fleet manager was brilliant, coordination was smooth. 10/10 would recommend.',
    rating: 5,
    avatar: 'AN',
  },
]
